// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpfplat

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type knokAllowKey struct {
	Ip   [16]uint8
	Port uint16
	Pad  uint16
}

type knokCfgVal struct {
	SpaPort uint32
	MinLen  uint32
	MaxLen  uint32
}

// loadKnok returns the embedded CollectionSpec for knok.
func loadKnok() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KnokBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load knok: %w", err)
	}

	return spec, err
}

// loadKnokObjects loads knok and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*knokObjects
//	*knokPrograms
//	*knokMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKnokObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKnok()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// knokSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type knokSpecs struct {
	knokProgramSpecs
	knokMapSpecs
	knokVariableSpecs
}

// knokProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type knokProgramSpecs struct {
	KnokIngress *ebpf.ProgramSpec `ebpf:"knok_ingress"`
}

// knokMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type knokMapSpecs struct {
	Allowlist *ebpf.MapSpec `ebpf:"allowlist"`
	Cfg       *ebpf.MapSpec `ebpf:"cfg"`
	SpaEvents *ebpf.MapSpec `ebpf:"spa_events"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
}

// knokVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type knokVariableSpecs struct {
}

// knokObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKnokObjects or ebpf.CollectionSpec.LoadAndAssign.
type knokObjects struct {
	knokPrograms
	knokMaps
	knokVariables
}

func (o *knokObjects) Close() error {
	return _KnokClose(
		&o.knokPrograms,
		&o.knokMaps,
	)
}

// knokMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKnokObjects or ebpf.CollectionSpec.LoadAndAssign.
type knokMaps struct {
	Allowlist *ebpf.Map `ebpf:"allowlist"`
	Cfg       *ebpf.Map `ebpf:"cfg"`
	SpaEvents *ebpf.Map `ebpf:"spa_events"`
	Stats     *ebpf.Map `ebpf:"stats"`
}

func (m *knokMaps) Close() error {
	return _KnokClose(
		m.Allowlist,
		m.Cfg,
		m.SpaEvents,
		m.Stats,
	)
}

// knokVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKnokObjects or ebpf.CollectionSpec.LoadAndAssign.
type knokVariables struct {
}

// knokPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKnokObjects or ebpf.CollectionSpec.LoadAndAssign.
type knokPrograms struct {
	KnokIngress *ebpf.Program `ebpf:"knok_ingress"`
}

func (p *knokPrograms) Close() error {
	return _KnokClose(
		p.KnokIngress,
	)
}

func _KnokClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed knok_bpfel.o
var _KnokBytes []byte
